/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eze
 * Interfaz que permite listar articulos segun su estado
 * Disponibles/No disponibles (para ser alquilados en una fecha determinada)
 * 
 */
public class DisponibilidadArticulosGui extends javax.swing.JInternalFrame {

    /**
     * Creates new form EstadoArticulosGui
     */
    public DisponibilidadArticulosGui() {
        initComponents();
    }

    public JDateChooser getDateFecha() {
        return dateFecha;
    }

    public JComboBox getComboDisponibilidad() {
        return comboDisponibilidad;
    }

    public JComboBox getComboTipo() {
        return comboTipo;
    }
    
    public String getDateFechaString() {
        if( dateFecha.getCalendar() != null){
            int año = dateFecha.getCalendar().get(Calendar.YEAR);
            int mes = dateFecha.getCalendar().get(Calendar.MONTH) + 1;
            int dia = dateFecha.getCalendar().get(Calendar.DAY_OF_MONTH);
            return año+"-"+mes+"-"+dia;
        }else{
            return null;
        }
    }

    public JTable getTablaDisponibilidadArticulos() {
        return tablaDisponibilidadArticulos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDisponibilidadArticulos = new javax.swing.JTable();
        comboDisponibilidad = new javax.swing.JComboBox();
        comboTipo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Artículos Disponibles");
        setPreferredSize(new java.awt.Dimension(1082, 575));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de Artículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel2.setText("Fecha");

        tablaDisponibilidadArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modelo", "Marca", "Tipo", "Talle", "Descripcion", "Precio", "Disponible", "Cant. Disp."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDisponibilidadArticulos);
        if (tablaDisponibilidadArticulos.getColumnModel().getColumnCount() > 0) {
            tablaDisponibilidadArticulos.getColumnModel().getColumn(0).setPreferredWidth(45);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(1).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(2).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(3).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(4).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(4).setPreferredWidth(45);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(5).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(6).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(6).setPreferredWidth(45);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(7).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(7).setPreferredWidth(40);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(8).setResizable(false);
            tablaDisponibilidadArticulos.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        comboDisponibilidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponibles", "Alquilados" }));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Ambo", "Camisa", "Corbata", "Chaleco", "Cinto", "Pantalón", "Saco", "Zapato" }));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel4.setText("Tipo");

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel5.setText("Disponibilidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboDisponibilidad;
    private javax.swing.JComboBox comboTipo;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDisponibilidadArticulos;
    // End of variables declaration//GEN-END:variables

    public void limpiarComponentes() {
        ((DefaultTableModel)this.tablaDisponibilidadArticulos.getModel()).setRowCount(0);
        this.dateFecha.setCalendar(null);
        this.comboTipo.setSelectedItem("Todos");
        this.comboDisponibilidad.setSelectedItem("Disponibles");
    }
    
    public void setActionListener(ActionListener lis) {
        this.comboDisponibilidad.addActionListener(lis);
        this.comboTipo.addActionListener(lis);
    }
}
