/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eze
 */
public class RemitoGui extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemitoGui
     */
    public RemitoGui() {
        initComponents();
    }

    public JButton getBttnCancelarRemito() {
        return bttnCancelarRemito;
    }

    public JButton getBttnEliminarRemito() {
        return bttnEliminarRemito;
    }

    
    public JButton getBttnGuardarRemito() {
        return bttnGuardarRemito;
    }

    public JTextField getBusquedaClienteRemito() {
        return busquedaClienteRemito;
    }

    public JCheckBox getjCheckConfirmarPago() {
        return jCheckConfirmarPago;
    }
    
    public JTextField getBusquedaCodigoArticulo() {
        return busquedaCodigoArticulo;
    }

    public String getFechaRemito() {
        if( jDateFechaRemito.getCalendar() !=null){
            int año = jDateFechaRemito.getCalendar().get(Calendar.YEAR);
            int mes = jDateFechaRemito.getCalendar().get(Calendar.MONTH) + 1;
            int dia = jDateFechaRemito.getCalendar().get(Calendar.DAY_OF_MONTH);
            return año+"-"+mes+"-"+dia;
        }else{
            return null;
        }
    }

    public JTextField getjTextNumeroRemito() {
        return jTextNumeroRemito;
    }

    public JTextField getjTextSeñaRemito() {
        return jTextSeñaRemito;
    }

    public JTextField getjTextTotalRemito() {
        return jTextTotalRemito;
    }

    public JTable getTablaArticulosRemito() {
        return tablaArticulosRemito;
    }

    public JTable getTablaBusquedaArticulosRemito() {
        return tablaBusquedaArticulosRemito;
    }

    public JTable getTablaClienteRemito() {
        return tablaClienteRemito;
    }

    public void setBusquedaClienteRemito(String busquedaClienteRemito) {
        this.busquedaClienteRemito.setText(busquedaClienteRemito);
    }

    public void setjDateFechaRemito(Date dateFechaRemito) {
        this.jDateFechaRemito.setDate(dateFechaRemito);
    }

    public void setjTextNumeroRemito(Object numeroRemito) {
        this.jTextNumeroRemito.setText((String) numeroRemito);
    }

    public void setjTextSeñaRemito(Object señaRemito) {
        this.jTextSeñaRemito.setText((String) señaRemito);
    }

    public void setjTextTotalRemito(Object totalRemito) {
        this.jTextTotalRemito.setText(totalRemito.toString());
    }
    
    public void limpiarComponentes(){
        this.jTextNumeroRemito.setText("");
        this.jTextSeñaRemito.setText("00.0");
        this.jTextTotalRemito.setText("00.0");
        this.busquedaClienteRemito.setText("");
        this.busquedaCodigoArticulo.setText("");
        this.jDateFechaRemito.setCalendar(null);
        this.jCheckConfirmarPago.setSelected(false);
        ((DefaultTableModel)this.tablaClienteRemito.getModel()).setRowCount(0);
        ((DefaultTableModel)this.tablaArticulosRemito.getModel()).setRowCount(0);
        ((DefaultTableModel)this.tablaBusquedaArticulosRemito.getModel()).setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();
        panelBusquedaArticulosRemito = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaBusquedaArticulosRemito = new javax.swing.JTable();
        labelBusquedaCodigo = new javax.swing.JLabel();
        busquedaCodigoArticulo = new javax.swing.JTextField();
        panelBusquedaClienteRemito = new javax.swing.JPanel();
        busquedaClienteRemito = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClienteRemito = new javax.swing.JTable();
        panelDatosYConfirmacionRemito = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNumeroRemito = new javax.swing.JTextField();
        jTextSeñaRemito = new javax.swing.JTextField();
        jTextTotalRemito = new javax.swing.JTextField();
        jDateFechaRemito = new com.toedter.calendar.JDateChooser();
        bttnGuardarRemito = new javax.swing.JButton();
        bttnEliminarRemito = new javax.swing.JButton();
        bttnCancelarRemito = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckConfirmarPago = new javax.swing.JCheckBox();
        panelArticulosRemito = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaArticulosRemito = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Remito");
        setPreferredSize(new java.awt.Dimension(1082, 575));

        panelBusquedaArticulosRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de Artículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        tablaBusquedaArticulosRemito.setAutoCreateRowSorter(true);
        tablaBusquedaArticulosRemito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modelo", "Marca", "Tipo", "Talle", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaBusquedaArticulosRemito);

        labelBusquedaCodigo.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelBusquedaCodigo.setText("Código");

        busquedaCodigoArticulo.setToolTipText("Buscar por Modelo, Marca,Tipo,Talle o Nombre de Ambo.");

        javax.swing.GroupLayout panelBusquedaArticulosRemitoLayout = new javax.swing.GroupLayout(panelBusquedaArticulosRemito);
        panelBusquedaArticulosRemito.setLayout(panelBusquedaArticulosRemitoLayout);
        panelBusquedaArticulosRemitoLayout.setHorizontalGroup(
            panelBusquedaArticulosRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaArticulosRemitoLayout.createSequentialGroup()
                .addGroup(panelBusquedaArticulosRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaArticulosRemitoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelBusquedaCodigo)
                        .addGap(54, 54, 54)
                        .addComponent(busquedaCodigoArticulo))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBusquedaArticulosRemitoLayout.setVerticalGroup(
            panelBusquedaArticulosRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaArticulosRemitoLayout.createSequentialGroup()
                .addGroup(panelBusquedaArticulosRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBusquedaCodigo)
                    .addComponent(busquedaCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBusquedaClienteRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        busquedaClienteRemito.setToolTipText("Buscar clientes por ID, Nombre o DNI");

        tablaClienteRemito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaClienteRemito);

        javax.swing.GroupLayout panelBusquedaClienteRemitoLayout = new javax.swing.GroupLayout(panelBusquedaClienteRemito);
        panelBusquedaClienteRemito.setLayout(panelBusquedaClienteRemitoLayout);
        panelBusquedaClienteRemitoLayout.setHorizontalGroup(
            panelBusquedaClienteRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaClienteRemitoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelBusquedaClienteRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(busquedaClienteRemito))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBusquedaClienteRemitoLayout.setVerticalGroup(
            panelBusquedaClienteRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaClienteRemitoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busquedaClienteRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosYConfirmacionRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel1.setText("Número");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel2.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel4.setText("TOTAL $");

        jTextNumeroRemito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroRemitoActionPerformed(evt);
            }
        });

        jTextTotalRemito.setEditable(false);
        jTextTotalRemito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalRemitoActionPerformed(evt);
            }
        });

        bttnGuardarRemito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/guardar.png"))); // NOI18N
        bttnGuardarRemito.setText("Guardar");
        bttnGuardarRemito.setToolTipText("Guardar Remito en Base de Datos");

        bttnEliminarRemito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/borrar.png"))); // NOI18N
        bttnEliminarRemito.setText("Eliminar");
        bttnEliminarRemito.setToolTipText("Borrar Remito de Base de Datos");

        bttnCancelarRemito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/cancelar.png"))); // NOI18N
        bttnCancelarRemito.setText("Cancelar");
        bttnCancelarRemito.setToolTipText("Descartar Remito");

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel5.setText("Seña  $");

        jCheckConfirmarPago.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jCheckConfirmarPago.setText("Pago Confirmado");
        jCheckConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckConfirmarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosYConfirmacionRemitoLayout = new javax.swing.GroupLayout(panelDatosYConfirmacionRemito);
        panelDatosYConfirmacionRemito.setLayout(panelDatosYConfirmacionRemitoLayout);
        panelDatosYConfirmacionRemitoLayout.setHorizontalGroup(
            panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosYConfirmacionRemitoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosYConfirmacionRemitoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumeroRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTotalRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFechaRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckConfirmarPago)
                        .addGroup(panelDatosYConfirmacionRemitoLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(4, 4, 4)
                            .addComponent(jTextSeñaRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)))
                    .addGroup(panelDatosYConfirmacionRemitoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(bttnGuardarRemito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnCancelarRemito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnEliminarRemito)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelDatosYConfirmacionRemitoLayout.setVerticalGroup(
            panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosYConfirmacionRemitoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextNumeroRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jDateFechaRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSeñaRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextTotalRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckConfirmarPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosYConfirmacionRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnGuardarRemito)
                    .addComponent(bttnEliminarRemito)
                    .addComponent(bttnCancelarRemito))
                .addGap(25, 25, 25))
        );

        panelArticulosRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Articulos del Remito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        tablaArticulosRemito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modelo", "Marca", "Tipo", "Talle", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaArticulosRemito);

        javax.swing.GroupLayout panelArticulosRemitoLayout = new javax.swing.GroupLayout(panelArticulosRemito);
        panelArticulosRemito.setLayout(panelArticulosRemitoLayout);
        panelArticulosRemitoLayout.setHorizontalGroup(
            panelArticulosRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArticulosRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        panelArticulosRemitoLayout.setVerticalGroup(
            panelArticulosRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArticulosRemitoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBusquedaArticulosRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelArticulosRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatosYConfirmacionRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBusquedaClienteRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBusquedaClienteRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBusquedaArticulosRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatosYConfirmacionRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelArticulosRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNumeroRemitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroRemitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroRemitoActionPerformed

    private void jCheckConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckConfirmarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckConfirmarPagoActionPerformed

    private void jTextTotalRemitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalRemitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalRemitoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancelarRemito;
    private javax.swing.JButton bttnEliminarRemito;
    private javax.swing.JButton bttnGuardarRemito;
    private javax.swing.JTextField busquedaClienteRemito;
    private javax.swing.JTextField busquedaCodigoArticulo;
    private javax.swing.JCheckBox jCheckConfirmarPago;
    private com.toedter.calendar.JDateChooser jDateFechaRemito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextNumeroRemito;
    private javax.swing.JTextField jTextSeñaRemito;
    private javax.swing.JTextField jTextTotalRemito;
    private javax.swing.JLabel labelBusquedaCodigo;
    private javax.swing.JPanel panelArticulosRemito;
    private javax.swing.JPanel panelBusquedaArticulosRemito;
    private javax.swing.JPanel panelBusquedaClienteRemito;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelDatosYConfirmacionRemito;
    private javax.swing.JTable tablaArticulosRemito;
    private javax.swing.JTable tablaBusquedaArticulosRemito;
    private javax.swing.JTable tablaClienteRemito;
    // End of variables declaration//GEN-END:variables

    public void setActionListener(ActionListener lis) {
        this.bttnGuardarRemito.addActionListener(lis);
        this.bttnEliminarRemito.addActionListener(lis);
        this.bttnCancelarRemito.addActionListener(lis);
        this.jCheckConfirmarPago.addActionListener(lis);
    }
}
