/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eze
 */
public class ReservaGui extends javax.swing.JInternalFrame {

    private final DefaultTableModel tablaArticulosDefault;
    
    /**
     * Creates new form Reserva
     */
    public ReservaGui() {
        initComponents();
        this.tablaArticulosDefault = (DefaultTableModel) tablaArticulos.getModel();//conveirto la tabla
    }

    public JTextField getBusquedaCliente() {
        return busquedaCliente;
    }

    public String getBusquedaCodigoArticulo() {
        return busquedaCodigoArticulo.getText();
    }

    public String getFechaEntregaReserva() {
        if( fechaEntregaReserva.getCalendar() != null){
            int año = fechaEntregaReserva.getCalendar().get(Calendar.YEAR);
            int mes = fechaEntregaReserva.getCalendar().get(Calendar.MONTH) + 1;
            int dia = fechaEntregaReserva.getCalendar().get(Calendar.DAY_OF_MONTH);
            return año+"-"+mes+"-"+dia;
        }else{
            return null;
        }
    }

    public String getFechaReserva() {
        if( fechaReserva.getCalendar() !=null){
            int año = fechaReserva.getCalendar().get(Calendar.YEAR);
            int mes = fechaReserva.getCalendar().get(Calendar.MONTH) + 1;
            int dia = fechaReserva.getCalendar().get(Calendar.DAY_OF_MONTH);
            return año+"-"+mes+"-"+dia;
        }else{
            return null;
        }
    }

    public DefaultTableModel getTablaArticulosDefault() {
        return tablaArticulosDefault;
    }

    public JTable getTablaClienteReserva() {
        return tablaClienteReserva;
    }


    public JButton getConfirmarReserva() {
        return confirmarReserva;
    }
    
    public void setFechaEntregaReserva(Date date) {
        this.fechaEntregaReserva.setDate(date);
    }

    public void setFechaReserva(Date date) {
        this.fechaReserva.setDate(date);
    }

    public void setBusquedaCliente(String busquedaCliente) {
        this.busquedaCliente.setText( busquedaCliente);
    }
    
    public void limpiarComponentes(){
        this.busquedaCliente.setText("");
        this.fechaEntregaReserva.setCalendar(null);
        this.fechaReserva.setCalendar(null);
        ((DefaultTableModel)this.tablaClienteReserva.getModel()).setRowCount(0);
        //falta limpiar parte de ariculos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();
        panelReservaArticulos = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        labelBusquedaCodigo = new javax.swing.JLabel();
        busquedaCodigoArticulo = new javax.swing.JTextField();
        panelClienteReserva = new javax.swing.JPanel();
        busquedaCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClienteReserva = new javax.swing.JTable();
        panelDatosYConfirmacionReserva = new javax.swing.JPanel();
        confirmarReserva = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fechaEntregaReserva = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        fechaReserva = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reserva");
        setPreferredSize(new java.awt.Dimension(1082, 575));

        panelReservaArticulos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        tablaArticulos.setAutoCreateRowSorter(true);
        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Modelo", "Marca", "Tipo", "Talle", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaArticulos);

        labelBusquedaCodigo.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        labelBusquedaCodigo.setText("Código");

        busquedaCodigoArticulo.setToolTipText("Filtrar por código");

        javax.swing.GroupLayout panelReservaArticulosLayout = new javax.swing.GroupLayout(panelReservaArticulos);
        panelReservaArticulos.setLayout(panelReservaArticulosLayout);
        panelReservaArticulosLayout.setHorizontalGroup(
            panelReservaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaArticulosLayout.createSequentialGroup()
                .addGroup(panelReservaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservaArticulosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelBusquedaCodigo)
                        .addGap(54, 54, 54)
                        .addComponent(busquedaCodigoArticulo))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelReservaArticulosLayout.setVerticalGroup(
            panelReservaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaArticulosLayout.createSequentialGroup()
                .addGroup(panelReservaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBusquedaCodigo)
                    .addComponent(busquedaCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelClienteReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 3, 18))); // NOI18N

        busquedaCliente.setToolTipText("Buscar clientes por ID, Nombre o DNI");

        tablaClienteReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaClienteReserva);
        if (tablaClienteReserva.getColumnModel().getColumnCount() > 0) {
            tablaClienteReserva.getColumnModel().getColumn(0).setResizable(false);
            tablaClienteReserva.getColumnModel().getColumn(0).setPreferredWidth(8);
            tablaClienteReserva.getColumnModel().getColumn(1).setResizable(false);
            tablaClienteReserva.getColumnModel().getColumn(2).setResizable(false);
            tablaClienteReserva.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        javax.swing.GroupLayout panelClienteReservaLayout = new javax.swing.GroupLayout(panelClienteReserva);
        panelClienteReserva.setLayout(panelClienteReservaLayout);
        panelClienteReservaLayout.setHorizontalGroup(
            panelClienteReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteReservaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelClienteReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(busquedaCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteReservaLayout.setVerticalGroup(
            panelClienteReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteReservaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosYConfirmacionReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        confirmarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Icons/agregar.png"))); // NOI18N
        confirmarReserva.setToolTipText("Confirmar Reserva");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel3.setText("Fecha de Retiro");

        fechaEntregaReserva.setToolTipText("Fecha en que se entrega la reserva al Cliente");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel2.setText("Fecha");

        fechaReserva.setToolTipText("Fecha en que se realiza la Reserva");

        javax.swing.GroupLayout panelDatosYConfirmacionReservaLayout = new javax.swing.GroupLayout(panelDatosYConfirmacionReserva);
        panelDatosYConfirmacionReserva.setLayout(panelDatosYConfirmacionReservaLayout);
        panelDatosYConfirmacionReservaLayout.setHorizontalGroup(
            panelDatosYConfirmacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosYConfirmacionReservaLayout.createSequentialGroup()
                .addGroup(panelDatosYConfirmacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosYConfirmacionReservaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelDatosYConfirmacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosYConfirmacionReservaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52)
                                .addComponent(fechaEntregaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosYConfirmacionReservaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(119, 119, 119)
                                .addComponent(fechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDatosYConfirmacionReservaLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(confirmarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelDatosYConfirmacionReservaLayout.setVerticalGroup(
            panelDatosYConfirmacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosYConfirmacionReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosYConfirmacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(panelDatosYConfirmacionReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(fechaEntregaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addComponent(panelReservaArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatosYConfirmacionReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelClienteReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelReservaArticulos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(panelClienteReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDatosYConfirmacionReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        jScrollPane1.setViewportView(panelContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busquedaCliente;
    private javax.swing.JTextField busquedaCodigoArticulo;
    private javax.swing.JButton confirmarReserva;
    private com.toedter.calendar.JDateChooser fechaEntregaReserva;
    private com.toedter.calendar.JDateChooser fechaReserva;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelBusquedaCodigo;
    private javax.swing.JPanel panelClienteReserva;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelDatosYConfirmacionReserva;
    private javax.swing.JPanel panelReservaArticulos;
    private javax.swing.JTable tablaArticulos;
    private javax.swing.JTable tablaClienteReserva;
    // End of variables declaration//GEN-END:variables

    public void setActionListener(ActionListener lis) {
        this.confirmarReserva.addActionListener(lis);
    }
}